
http://localhost:3000/pedido

###
POST http://localhost:3000/pedido HTTP/1.1
content-type: application/json

{
    "nome": "Santos Ferreira",
    "telefone": "11995421492",
    "endereco": "Rua 10",
    "mensagem": "rest client"
}
###

DELETE  https://example.com/topics/1 HTTP/1.1

###

PUT  https://example.com/topics/1 HTTP/1.1

###

PATCH  https://example.com/topics/1 HTTP/1.1
